import { useState } from 'react';
import { Mail } from 'lucide-react';
import { get } from '../../lib/api';
import { fmtDateTime } from '../../lib/format';
import { Alert, Badge, Card, EmptyState, ErrorBox, PageHeader, Select, Spinner, useLoad } from '../../components/ui';

const TYPES = ['ACCOUNT_CREATED', 'APPLICATION_SUBMITTED', 'APPLICATION_COPY', 'REFEREE_REQUEST', 'INTERVIEW_NOTIFICATION', 'SHORTLIST_SHARED', 'PASSWORD_RESET'];

export default function Outbox() {
  const [type, setType] = useState('');
  const { data, loading, error } = useLoad(() => get(`/admin/notifications${type ? `?type=${type}` : ''}`), [type]);
  const [open, setOpen] = useState(null);
  return (
    <>
      <PageHeader title="Email Outbox" subtitle="Emails generated by the system and their delivery status." />
      {data && !data.smtp_configured && (
        <Alert type="warning" className="mb-4" title="SMTP is not configured">
          Emails are being written to the server outbox folder instead of being delivered. Configure SMTP_HOST, SMTP_USER and SMTP_PASS for production.
        </Alert>
      )}
      <div className="mb-4 max-w-xs">
        <Select label="Type" value={type} onChange={(e) => setType(e.target.value)} placeholder="All types" options={TYPES.map((t) => ({ value: t, label: t.replace(/_/g, ' ').toLowerCase() }))} />
      </div>
      <ErrorBox error={error} />
      <Card bodyClass="p-0">
        {loading ? (
          <Spinner />
        ) : !data.notifications.length ? (
          <EmptyState icon={Mail} title="No emails" />
        ) : (
          <ul className="divide-y divide-slate-200">
            {data.notifications.map((n) => (
              <li key={n.id}>
                <button type="button" className="w-full px-5 py-3 text-left hover:bg-slate-50" onClick={() => setOpen(open === n.id ? null : n.id)} aria-expanded={open === n.id}>
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <span className="font-medium text-slate-900">{n.subject}</span>
                    <span className="flex items-center gap-2 text-xs text-slate-500">
                      <Badge tone={n.status === 'SENT' ? 'green' : n.status === 'FAILED' ? 'red' : 'amber'}>{n.status}</Badge>
                      {fmtDateTime(n.created_at)}
                    </span>
                  </div>
                  <p className="text-xs text-slate-500">
                    To {n.recipient_email} · {n.type.replace(/_/g, ' ').toLowerCase()}
                    {n.reference_no && ` · ${n.reference_no}`}
                  </p>
                  {n.error && <p className="text-xs text-red-600">{n.error}</p>}
                  {open === n.id && <pre className="mt-3 whitespace-pre-wrap rounded bg-slate-50 p-3 font-sans text-sm text-slate-700">{n.body}</pre>}
                </button>
              </li>
            ))}
          </ul>
        )}
      </Card>
    </>
  );
}
