// src/components/admin/ReferenceNoField.tsx
// Drop into the admin "New Advertisement" form in place of the manual
// Reference No. input. The number is a gap-free series (e.g. UOP/REC/2026/0007)
// generated by the server; this field only shows a preview — the real number
// is assigned atomically when the advertisement is saved, so two admins
// creating ads at the same time never get the same number.
//
//   <ReferenceNoField value={form.reference_no} />          // new ad  → preview
//   <ReferenceNoField value={vacancy.reference_no} />       // edit ad → assigned no.
import React, { useEffect, useState } from "react";
import { Hash, Loader2, RefreshCw } from "lucide-react";
import { getNextVacancyReference } from "../../services/applicationApi";

interface Props {
  /** Already-assigned reference (when editing an existing advertisement). */
  value?: string;
  label?: string;
}

const ReferenceNoField: React.FC<Props> = ({ value, label = "Reference No." }) => {
  const [preview, setPreview] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const load = async () => {
    setLoading(true);
    setError("");
    const res = await getNextVacancyReference();
    setLoading(false);
    if (res.success && res.data?.reference_no) setPreview(res.data.reference_no);
    else setError(res.error || "Could not fetch the next reference number.");
  };

  useEffect(() => {
    if (!value) void load();
  }, [value]);

  return (
    <div>
      <label className="block mb-1 text-sm font-medium text-gray-700">{label}</label>
      <div className="flex items-center gap-2 px-3 min-h-[44px] border border-gray-300 rounded-lg bg-gray-50">
        <Hash size={16} className="text-gray-400 shrink-0" />
        {loading ? (
          <Loader2 size={16} className="text-gray-400 animate-spin" />
        ) : (
          <span className="flex-1 font-mono text-sm text-gray-900">{value || preview || "—"}</span>
        )}
        {!value && !loading && (
          <button type="button" onClick={load} className="p-1 text-gray-500 hover:text-gray-800" aria-label="Refresh">
            <RefreshCw size={14} />
          </button>
        )}
      </div>
      <p className={`mt-1 text-xs ${error ? "text-red-600" : "text-gray-500"}`}>
        {error ||
          (value
            ? "Assigned automatically. Use it to search for this advertisement and its applications."
            : "Generated automatically — the next number in the series is assigned when you save.")}
      </p>
    </div>
  );
};

export default ReferenceNoField;
